- name: Instalar o puppet - DEBIAN
  command: dpkg -i /var/puppet.deb
  when: ansible_os_family == "Debian"


- name: Instalar o puppet-agent - DEBIAN
  apt: name=puppet-agent state=present update_cache=yes
  when: ansible_os_family == "Debian"

