---

- name: Instalando GITLAB
  hosts: devops
  tasks: 
    - name: Instalando pacotes
      apt: 
        name: "{{ item }}"
        state: present
        update-cache: yes
      with_items:
      - curl 
      - openssh-server
      - ca-certificates
      
    - name: Executando Script - GITLAB
      shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash

    - name: Intalando pacote - GITLAB
      apt: name=gitlab-ce state=present

